### ISSUE TITLE
Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'WooAmoConnector_Walker'

### ISSUE THREAD

**Issue by uptimizt** [wpcraft-ru/wooamoconnector#9]
Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'WooAmoConnector_Walker' does not have a method 'hook_on_add_product' in /srv/www/wp-includes/class-wp-hook.php on line 286

ошибка появляется в теме OceanWP при попытке добавить продукт в Корзину

**Comment by artikus11** [comment]
@uptimizt Эта ошибка должна появляться в любой теме. На хук вешается метод, которого нет в классе https://github.com/wpcraft-ru/wooamoconnector/blob/master/inc/class-root-wooac.php#L11 Надо или хук не вызывать или метод объявить

**Comment by aiiddqd** [comment]
да, поправил https://github.com/wpcraft-ru/wooamoconnector/commit/67ba0298432be754bd597d3dcc76b4f1c1434260
